### PR TITLE
Replace createMacroConnections with createMacroConnectionsOrSkip

### LINKED ISSUE #576: Replace exception prone macro connection creation
### Describe the current behavior

`createMacroConnections` is used in several models.
if the requested model is not found an exception is thrown

### Describe the expected behavior

Replace `createMacroConnections` with `createMacroConnectionsOrSkip` and handle the returned value.
For example, if no macro connection can be created the model should be skipped and reported.

### Describe the motivation

Launch the simulation even if some data are incorrect.

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by RiadBRD**
**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A PR or issue has been opened in all impacted repositories (if any)

**Does this PR already have an issue describing the problem?**
Fixes #576

**What kind of change does this PR introduce?**
feature

**What is the new behavior (if this is a feature change)?**
Replace `createMacroConnections` with `createMacroConnectionsOrSkip` in:
- `EventActivePowerVariation`
- `EventReactivePowerVariation`
- `EventReferenceVoltageVariation`

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [x] No

### CODE REVIEW

File: dynawo-simulation/src/test/java/com/powsybl/dynawo/xml/EmptyReactivePowerVariationEventXmlTest.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+import com.powsybl.iidm.network.test.EurostagTutorialExample1Factory;
+import org.junit.jupiter.api.Test;
+import org.xml.sax.SAXException;
+
+import java.io.IOException;
+
+/**
+ * @author Riad Benradi {@literal <riad.benradi at rte-france.com>}
+ */
+
```
Comment (Lisrte) [inline dynawo-simulation/src/test/java/com/powsybl/dynawo/xml/EmptyReactivePowerVariationEventXmlTest.java]: empty line

File: dynawo-simulation/src/test/java/com/powsybl/dynawo/xml/EmptyActivePowerVariationEventXmlTest.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
+package com.powsybl.dynawo.xml;
```
Comment (Lisrte) [inline dynawo-simulation/src/test/java/com/powsybl/dynawo/xml/EmptyActivePowerVariationEventXmlTest.java]: missing copyright (same things for the other tests)

File: dynawo-simulation/src/main/java/com/powsybl/dynawo/models/events/EventActivePowerVariation.java [hunk 3]
```diff
@@ -35,15 +36,15 @@ private List<VarConnection> getVarConnectionsWith(PControllableEquipmentModel co
...
+        isSkipped = adder.createMacroConnectionsOrSkip(this, getEquipment(), PControllableEquipmentModel.class, this::getVarConnectionsWith);
+        if (isSkipped) {
+            DynawoSimulationReports.reportFailedDynamicModelHandling(adder.getReportNode(), getName(), getDynamicModelId(), getEquipment().getType().toString());
+        }
     }
 
     @Override
     public void createNetworkParameter(ParametersSet networkParameters) {
-        if (equipmentModelType.getValue().equals(EquipmentModelType.DEFAULT_LOAD)) {
+        if (equipmentModelType.getValue().equals(EquipmentModelType.DEFAULT_LOAD) && !isSkipped) {
```
Comment (Lisrte) [inline dynawo-simulation/src/main/java/com/powsybl/dynawo/models/events/EventActivePowerVariation.java]:
```suggestion
        if (!isSkipped && equipmentModelType.getValue().equals(EquipmentModelType.DEFAULT_LOAD)) {
```

**Review by Lisrte — CHANGES_REQUESTED** [review]
